# Nombre del workflow (aparecerá en la GUI)
name: Workflou actions
# Cuándo se ejecuta: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: push
# Listado de jobs
jobs:
  # ID del job. Cada job se ejecuta en una máquina nueva
  my-job:
    # Tipo de máquina. Puede ser de Github o un self-hosted runner:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
    - name: Descargamos código
      uses: actions/checkout@v3
    - name: Instalamos Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1'
    - name: Test unitarios
      run: go test ./...
    - name: Creamos imagen de Docker
      run: docker build -t miimagenmolona .