# Nombre del workflow (aparecerá en la GUI)
name: Workflou actions
# Cuándo se ejecuta: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: 
  pull_request:
    branches:    
      - main
# Listado de jobs
jobs:
  # ID del job. Cada job se ejecuta en una máquina nueva
  Accioneando:
    # Tipo de máquina. Puede ser de Github o un self-hosted runner:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
    - name: Descargamos código
      uses: actions/checkout@v3

    - name: Instalamos Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1'

    - name: Test unitarios
      run: go test ./...

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build, tag, and push the image to Amazon ECR
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: "ghcr.io/pabloruizSignaturit/curso8:${{ github.sha }}"
      

    
